services:
  db:
    image: postgres:14-alpine
    container_name: concrete_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: concrete_map_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: concrete_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=concrete_map_db;Username=postgres;Password=mysecretpassword;Trust Server Certificate=True
      - JwtSettings__Key=SuperSecretKey_ConcreteMap_2025_LongEnoughToBeSecure!
      - JwtSettings__Issuer=ConcreteMapServer
      - JwtSettings__Audience=ConcreteMapClient
      - YandexMaps__ApiKey=afd7a82d-03c7-4669-99e5-788fcb485888
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure

volumes:
  postgres_data: